### ISSUE TITLE
[meta] Tracking issue for r0.4.0 compatibility

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client#21]
*Based on [the changelog for r0.4.0](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst#r040). ToDo: Add new endpoints, implement upstream changes, review spec clarifications.*

New Endpoints
-------------

- [ ] `POST /user_directory/search` (<https://github.com/matrix-org/matrix-doc/issues/1096>)
- [ ] `GET /rooms/{roomId}/event/{eventId}` (<https://github.com/matrix-org/matrix-doc/issues/1110>)
- [ ] `POST /delete_devices` (<https://github.com/matrix-org/matrix-doc/issues/1239>)
- [ ] `GET /thirdparty/*` Endpoints (<https://github.com/matrix-org/matrix-doc/issues/1353>)
- [ ] `POST /account/3pid/msisdn/requestToken`, `POST /register/msisdn/requestToken`, and `POST /account/password/msisdn/requestToken` (<https://github.com/matrix-org/matrix-doc/issues/1507>)
- [ ] `POST /account/3pid/delete` (<https://github.com/matrix-org/matrix-doc/issues/1567>)
- [ ] `POST /rooms/{roomId}/read_markers` (<https://github.com/matrix-org/matrix-doc/issues/1635>)

Backwards Compatible Changes
----------------------------

- [ ] Add more presence options to the `set_presence` parameter of `/sync`. (Thanks @mujx!) (<https://github.com/matrix-org/matrix-doc/issues/780>)
- [ ] Add `token` parameter to the `/keys/query` endpoint (<https://github.com/matrix-org/matrix-doc/issues/1104>)
- [ ] Add the room visibility options for the room directory (<https://github.com/matrix-org/matrix-doc/issues/1141>)
- [ ] Add spec for ignoring users (<https://github.com/matrix-org/matrix-doc/issues/1142>)
- [ ] Add the `/register/available` endpoint for username availability (<https://github.com/matrix-org/matrix-doc/issues/1151>)
- [ ] Add sticker messages (<https://github.com/matrix-org/matrix-doc/issues/1158>)
- [ ] Specify how to control the power level required for `@room` (<https://github.com/matrix-org/matrix-doc/issues/1176>)
- [ ] Document `/logout/all` endpoint (<https://github.com/matrix-org/matrix-doc/issues/1263>)
- [ ] Add report content API (<https://github.com/matrix-org/matrix-doc/issues/1264>)
- [ ] Add `allow_remote` to the content repo to avoid routing loops (<https://github.com/matrix-org/matrix-doc/issues/1265>)
- [ ] Document highlights field in /search response (<https://github.com/matrix-org/matrix-doc/issues/1274>)
- [ ] End-to-end encryption for group chats:

  * Olm and Megolm messaging algorithms.
  * `m.room.encrypted`, `m.room.encryption`, `m.room_key` events.
  * Device verification process.
  * `device_one_time_keys_count` sync parameter.
  * `device_lists:left` sync parameter. (<https://github.com/matrix-org/matrix-doc/issues/1284>)
- [ ] Add `.well-known` server discovery method (<https://github.com/matrix-org/matrix-doc/issues/1359>)
- [ ] Document the GET version of `/login` (<https://github.com/matrix-org/matrix-doc/issues/1361>)
- [ ] Document the `server_name` parameter on `/join/{roomIdOrAlias}` (<https://github.com/matrix-org/matrix-doc/issues/1364>)
- [ ] Document the CORS/preflight headers (<https://github.com/matrix-org/matrix-doc/issues/1365>)
- [ ] Add new user identifier object for logging in (<https://github.com/matrix-org/matrix-doc/issues/1390>)
- [ ] Document message formats on `m.text` and `m.emote` messages (<https://github.com/matrix-org/matrix-doc/issues/1397>)
- [ ] Encrypt file attachments (<https://github.com/matrix-org/matrix-doc/issues/1420>)
- [ ] Share room decryption keys between devices (<https://github.com/matrix-org/matrix-doc/issues/1465>)
- [ ] Document and improve client interaction with pushers. (<https://github.com/matrix-org/matrix-doc/issues/1506>)
- [ ] Add support for Room Versions. (<https://github.com/matrix-org/matrix-doc/issues/1516>)
- [ ] Guests can now call /context and /event to fetch events (<https://github.com/matrix-org/matrix-doc/issues/1542>)
- [ ] Add a common standard for user, room, and group mentions in messages. (<https://github.com/matrix-org/matrix-doc/issues/1547>)
- [ ] Add server ACLs as an option for controlling federation in a room. (<https://github.com/matrix-org/matrix-doc/issues/1550>)
- [ ] Add new push rules for encrypted events and `@room` notifications. (<https://github.com/matrix-org/matrix-doc/issues/1551>)
- [ ] Add third party network room directories, as provided by application services. (<https://github.com/matrix-org/matrix-doc/issues/1554>)
- [ ] Document the `validated_at` and `added_at` fields on `GET /acount/3pid`. (<https://github.com/matrix-org/matrix-doc/issues/1567>)
- [ ] Add an `inhibit_login` registration option. (<https://github.com/matrix-org/matrix-doc/issues/1589>)
- [ ] Recommend that servers set a Content Security Policy for the content repository. (<https://github.com/matrix-org/matrix-doc/issues/1600>)
- [ ] Add "rich replies" - a way for users to better represent the conversation thread they are referencing in their messages. (<https://github.com/matrix-org/matrix-doc/issues/1617>)
- [ ] Add support for read markers. (<https://github.com/matrix-org/matrix-doc/issues/1635>)

Spec Clarifications
-------------------

- [ ] Mark `home_server` return field for `/login` and `/register` endpoints as deprecated (<https://github.com/matrix-org/matrix-doc/issues/1097>)
- [ ] Fix response format of `/keys/changes` endpoint (<https://github.com/matrix-org/matrix-doc/issues/1106>)
- [ ] Clarify default values for some fields on the `/search` API (<https://github.com/matrix-org/matrix-doc/issues/1109>)
- [ ] Fix the representation of `m.presence` events (<https://github.com/matrix-org/matrix-doc/issues/1137>)
- [ ] Clarify that `m.tag` ordering is done with numbers, not strings (<https://github.com/matrix-org/matrix-doc/issues/1139>)
- [ ] Clarify that `/account/whoami` should consider application services (<https://github.com/matrix-org/matrix-doc/issues/1152>)
- [ ] Update `ImageInfo` and `ThumbnailInfo` dimension schema descriptions to clarify that they relate to intended display size, as opposed to the intrinsic size of the image file. (<https://github.com/matrix-org/matrix-doc/issues/1158>)
- [ ] Mark `GET /rooms/{roomId}/members` as requiring authentication (<https://github.com/matrix-org/matrix-doc/issues/1245>)
- [ ] Clarify `changed` field behaviour in device tracking process (<https://github.com/matrix-org/matrix-doc/issues/1284>)
- [ ] Describe `StateEvent` for `/createRoom` (<https://github.com/matrix-org/matrix-doc/issues/1329>)
- [ ] Describe how the `reason` is handled for kicks/bans (<https://github.com/matrix-org/matrix-doc/issues/1362>)
- [ ] Mark `GET /presence/{userId}/status` as requiring authentication (<https://github.com/matrix-org/matrix-doc/issues/1371>)
- [ ] Describe the rate limit error response schema (<https://github.com/matrix-org/matrix-doc/issues/1373>)
- [ ] Clarify that clients must leave rooms before forgetting them (<https://github.com/matrix-org/matrix-doc/issues/1378>)
- [ ] Document guest access in `/createRoom` presets (<https://github.com/matrix-org/matrix-doc/issues/1379>)
- [ ] Define what a `RoomEvent` is on `/rooms/{roomId}/messages` (<https://github.com/matrix-org/matrix-doc/issues/1380>)
- [ ] Clarify the request and result types on `/search` (<https://github.com/matrix-org/matrix-doc/issues/1381>)
- [ ] Clarify some of the properties on the search result (<https://github.com/matrix-org/matrix-doc/issues/1400>)
- [ ] Clarify how access tokens are meant to be supplied to the homeserver. (<https://github.com/matrix-org/matrix-doc/issues/1517>)
- [ ] Document additional parameters on the `/createRoom` API. (<https://github.com/matrix-org/matrix-doc/issues/1518>)
- [ ] Clarify that new push rules should be enabled by default, and that unrecognised conditions should not match. (<https://github.com/matrix-org/matrix-doc/issues/1551>)
- [ ] Update all event examples to be accurate representations of their associated events. (<https://github.com/matrix-org/matrix-doc/issues/1558>)
- [ ] Clarify the supported HTML features for room messages. (<https://github.com/matrix-org/matrix-doc/issues/1562>)
- [ ] Move the `invite_room_state` definition under `unsigned` where it actually resides. (<https://github.com/matrix-org/matrix-doc/issues/1568>)
- [ ] Clarify the homeserver's behaviour for searching users. (<https://github.com/matrix-org/matrix-doc/issues/1569>)
- [ ] Clarify the object structures and defaults for Filters. (<https://github.com/matrix-org/matrix-doc/issues/1570>)
- [ ] Clarify instances of `type: number` in the swagger/OpenAPI schema definitions. (<https://github.com/matrix-org/matrix-doc/issues/1571>)
- [ ] Clarify that left rooms also have account data in `/sync`. (<https://github.com/matrix-org/matrix-doc/issues/1572>)
- [ ] Clarify the event fields used in the `/sync` response. (<https://github.com/matrix-org/matrix-doc/issues/1573>)
- [ ] Fix naming of the body field in `PUT /directory/room`. (<https://github.com/matrix-org/matrix-doc/issues/1574>)
- [ ] Clarify the filter object schema used in room searching. (<https://github.com/matrix-org/matrix-doc/issues/1577>)
- [ ] Document the 403 error for sending state events. (<https://github.com/matrix-org/matrix-doc/issues/1590>)
- [ ] specify how to handle multiple olm sessions with the same device (<https://github.com/matrix-org/matrix-doc/issues/1596>)
- [ ] Add the other keys that redactions are expected to preserve. (<https://github.com/matrix-org/matrix-doc/issues/1602>)
- [ ] Clarify that clients should not be generating invalid HTML for formatted events. (<https://github.com/matrix-org/matrix-doc/issues/1605>)
- [ ] Clarify the room tag structure (thanks @KitsuneRal!) (<https://github.com/matrix-org/matrix-doc/issues/1606>)
- [ ] Add a note that clients may use the transaction ID to avoid flickering when doing local echo. (<https://github.com/matrix-org/matrix-doc/issues/1619>)
- [ ] Include the request and response structures for the various `/requestToken` endpoints. (<https://github.com/matrix-org/matrix-doc/issues/1636>)
- [ ] Clarify the available error codes, and when to prefer the HTTP status code over the `errcode`. (<https://github.com/matrix-org/matrix-doc/issues/1637>)
- [ ] Clarify and generalise the language used for describing pagination. (<https://github.com/matrix-org/matrix-doc/issues/1642>)
