### ISSUE TITLE
[meta] Tracking issue for r0.3.0 compatibility

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client#22]
*Based on [the changelog for r0.3.0](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst#r030). ToDo: Add new endpoints, implement upstream changes, review spec clarifications.*

When looking at one of the latest PRs again, I noticed it actually added an endpoint that's been in the spec since r0.3.0. And here I was thinking we only had to implement the changes from r0.3.0 to r0.4.0...

## New endpoints

- [x] `GET /joined_rooms` (<https://github.com/matrix-org/matrix-doc/pull/999>):  https://github.com/ruma/ruma-client-api/pull/34, #17
- [ ] `GET /rooms/{roomId}/joined_members` (<https://github.com/matrix-org/matrix-doc/pull/999>)
- [ ] `GET /account/whoami` (<https://github.com/matrix-org/matrix-doc/pull/1063>)
- [ ] `GET /media/{version}/preview_url` (<https://github.com/matrix-org/matrix-doc/pull/1064>)

## Breaking changes

- [ ] Change the rule kind of `.m.rule.contains_display_name` from
  `underride` to `override`. This works with all known clients
  which support push rules, but any other clients implementing
  the push rules API should be aware of this change. This
  makes it simple to mute rooms correctly in the API
  (<https://github.com/matrix-org/matrix-doc/pull/373>)
- [ ] Remove `/tokenrefresh` from the API
  (<https://github.com/matrix-org/matrix-doc/pull/395>)
- [ ] Remove requirement that tokens used in token-based login be macaroons
  (<https://github.com/matrix-org/matrix-doc/pull/395>)
- [ ] Move `thumbnail_url` and `thumbnail_info` members of json objects
  for `m.room.message` events with msgtypes `m.image`, `m.file`
  and `m.location`, inside the `info` member, to match `m.video`
  events (<https://github.com/matrix-org/matrix-doc/pull/723>)

## Backwards-compatiible changes

- [ ] Add `filename` parameter to `POST /_matrix/media/r0/upload`
  (<https://github.com/matrix-org/matrix-doc/pull/364>)
- [ ] Document CAS-based client login and the use of `m.login.token` in
  `/login` (<https://github.com/matrix-org/matrix-doc/pull/367>)
- [ ] Make `origin_server_ts` a mandatory field of room events
  (<https://github.com/matrix-org/matrix-doc/pull/370>)
- [ ] Add top-level `account_data` key to the responses to `GET /sync` and
  `GET /initialSync`
  (<https://github.com/matrix-org/matrix-doc/pull/380>)
- [ ] Add `is_direct` flag to `POST /createRoom` and invite member event
  Add 'Direct Messaging' module
  (<https://github.com/matrix-org/matrix-doc/pull/389>)
- [ ] Add `contains_url` option to `RoomEventFilter`
  (<https://github.com/matrix-org/matrix-doc/pull/390>)
- [ ] Add `filter` optional query param to `/messages`
  (<https://github.com/matrix-org/matrix-doc/pull/390>)
- [ ] Add 'Send-to-Device messaging' module
  (<https://github.com/matrix-org/matrix-doc/pull/386>)
- [ ] Add 'Device management' module
  (<https://github.com/matrix-org/matrix-doc/pull/402>)
- [ ] Require that User-Interactive auth fallback pages call
  `window.postMessage` to notify apps of completion
  (<https://github.com/matrix-org/matrix-doc/pull/398>)
- [ ] Add pagination and filter support to `/publicRooms`. Change response to
  omit fields rather than return `null`. Add estimate of total number of
  rooms in list
  (<https://github.com/matrix-org/matrix-doc/pull/388>)
- [ ] Allow guest accounts to use a number of endpoints which are required for
  end-to-end encryption
  (<https://github.com/matrix-org/matrix-doc/pull/751>)
- [ ] Add key distribution APIs, for use with end-to-end encryption
  (<https://github.com/matrix-org/matrix-doc/pull/894>)
- [ ] Add `m.room.pinned_events` state event for rooms
  (<https://github.com/matrix-org/matrix-doc/pull/1007>)
- [ ] Add mention of ability to send Access Token via an Authorization Header
- [ ] Add `guest_can_join` parameter to `POST /createRoom`
  (<https://github.com/matrix-org/matrix-doc/pull/1093>)

# Spec clarifications

- [ ] Add endpoints and logic for invites and third-party invites to the federation
  spec and update the JSON of the request sent by the identity server upon 3PID
  binding
  (<https://github.com/matrix-org/matrix-doc/pull/997>)
- [ ] Fix "membership" property on third-party invite upgrade example
  (<https://github.com/matrix-org/matrix-doc/pull/995>)
- [ ] Fix response format and 404 example for room alias lookup
  (<https://github.com/matrix-org/matrix-doc/pull/960>)
- [ ] Fix examples of `m.room.member` event and room state change,
  and added a clarification on the membership event sent upon profile update
  (<https://github.com/matrix-org/matrix-doc/pull/950>)
- [ ] Spell out the way that state is handled by `POST /createRoom`
  (<https://github.com/matrix-org/matrix-doc/pull/362>)
- [ ] Clarify the fields which are applicable to different types of push rule
  (<https://github.com/matrix-org/matrix-doc/pull/365>)
- [ ] A number of clarifications to authentication
  (<https://github.com/matrix-org/matrix-doc/pull/371>)
- [ ] Correct references to `user_id` which should have been `sender`
  (<https://github.com/matrix-org/matrix-doc/pull/376>)
- [ ] Correct inconsistent specification of `redacted_because` fields and their
  values (<https://github.com/matrix-org/matrix-doc/pull/378>)
- [ ] Mark required fields in response objects as such
  (<https://github.com/matrix-org/matrix-doc/pull/394>)
- [ ] Make `m.notice` description a bit harder in its phrasing to try to
  dissuade the same issues that occurred with IRC
  (<https://github.com/matrix-org/matrix-doc/pull/750>)
- [ ] `GET /user/{userId}/filter/{filterId}` requires authentication
  (<https://github.com/matrix-org/matrix-doc/pull/1003>)
- [ ] Add some clarifying notes on the behaviour of rooms with no
  `m.room.power_levels` event
  (<https://github.com/matrix-org/matrix-doc/pull/1026>)
- [ ] Clarify the relationship between `username` and `user_id` in the
  `/register` API
  (<https://github.com/matrix-org/matrix-doc/pull/1032>)
- [ ] Clarify rate limiting and security for content repository
  (<https://github.com/matrix-org/matrix-doc/pull/1064>)
