### ISSUE TITLE
[meta] Tracking issue for r0.5.0 compatibility

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client#25]
*Based on [the changelog for r0.5.0](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst#r050). ToDo: Add new endpoints, implement upstream changes, review spec clarifications.*

Breaking Changes
----------------

- [ ] Add a new `submit_url` field to the responses of `/requestToken` which older clients will not be able to handle correctly. (<https://github.com/matrix-org/matrix-doc/issues/2101>)

Deprecations
------------

- [ ] Remove references to presence lists. (<https://github.com/matrix-org/matrix-doc/issues/1817>)

New Endpoints
-------------

- [ ] `GET /account_data` routes. (<https://github.com/matrix-org/matrix-doc/issues/1873>)

Backwards Compatible Changes
----------------------------

- [ ] Add megolm session export format. (<https://github.com/matrix-org/matrix-doc/issues/1701>)
- [ ] Add support for advertising experimental features to clients. (<https://github.com/matrix-org/matrix-doc/issues/1786>)
- [ ] Add a generic SSO login API. (<https://github.com/matrix-org/matrix-doc/issues/1789>)
- [ ] Add a mechanism for servers to redirect clients to an alternative homeserver after logging in. (<https://github.com/matrix-org/matrix-doc/issues/1790>)
- [ ] Add room version upgrades. (<https://github.com/matrix-org/matrix-doc/issues/1791>`_, `#1875 <https://github.com/matrix-org/matrix-doc/issues/1875>)
- [ ] Support optional features by having clients query for capabilities. (<https://github.com/matrix-org/matrix-doc/issues/1829>`_, `#1879 <https://github.com/matrix-org/matrix-doc/issues/1879>)
- [ ] Add `M_RESOURCE_LIMIT_EXCEEDED` as an error code for when homeservers exceed limits imposed on them. (<https://github.com/matrix-org/matrix-doc/issues/1874>)
- [ ] Emit `M_UNSUPPORTED_ROOM_VERSION` error codes where applicable on `/createRoom` and `/invite` APIs. (<https://github.com/matrix-org/matrix-doc/issues/1908>)
- [ ] Add a `.m.rule.tombstone` default push rule for room ugprade notifications. (<https://github.com/matrix-org/matrix-doc/issues/2020>)
- [ ] Add support for sending server notices to clients. (<https://github.com/matrix-org/matrix-doc/issues/2026>)
- [ ] Add MSISDN (phone number) support to User-Interactive Authentication. (<https://github.com/matrix-org/matrix-doc/issues/2030>)
- [ ] Add the option to lazy-load room members for increased client performance. (<https://github.com/matrix-org/matrix-doc/issues/2035>)
- [ ] Add `id_server` to `/deactivate` and `/3pid/delete` endpoints to unbind from a specific identity server. (<https://github.com/matrix-org/matrix-doc/issues/2046>)
- [ ] Add support for Olm sessions becoming un-stuck. (<https://github.com/matrix-org/matrix-doc/issues/2059>)
- [ ] Add interactive device verification, including a common framework for device verification. (<https://github.com/matrix-org/matrix-doc/issues/2072>)

Spec Clarifications
-------------------

- [ ] Change examples to use example.org instead of a real domain. (<https://github.com/matrix-org/matrix-doc/issues/1650>)
- [ ] Clarify that `state_default` in `m.room.power_levels` always defaults to 50. (<https://github.com/matrix-org/matrix-doc/issues/1656>)
- [ ] Add missing `status_msg` to `m.presence` schema. (<https://github.com/matrix-org/matrix-doc/issues/1744>)
- [ ] Fix various spelling mistakes throughout the specification. (<https://github.com/matrix-org/matrix-doc/issues/1838>`_, `#1853 <https://github.com/matrix-org/matrix-doc/issues/1853>`_, `#1860 <https://github.com/matrix-org/matrix-doc/issues/1860>`_, `#1933 <https://github.com/matrix-org/matrix-doc/issues/1933>`_, `#1969 <https://github.com/matrix-org/matrix-doc/issues/1969>`_, `#1988 <https://github.com/matrix-org/matrix-doc/issues/1988>`_, `#1989 <https://github.com/matrix-org/matrix-doc/issues/1989>`_, `#1991 <https://github.com/matrix-org/matrix-doc/issues/1991>`_, `#1992 <https://github.com/matrix-org/matrix-doc/issues/1992>)
- [ ] Add the missing `m.push_rules` event schema. (<https://github.com/matrix-org/matrix-doc/issues/1889>)
- [ ] Clarify how modern day local echo is meant to be solved by clients. (<https://github.com/matrix-org/matrix-doc/issues/1891>)
- [ ] Clarify that `width` and `height` are required parameters on `/_matrix/media/r0/thumbnail/{serverName}/{mediaId}`. (<https://github.com/matrix-org/matrix-doc/issues/1975>)
- [ ] Clarify how `m.login.dummy` can be used to disambiguate login flows. (<https://github.com/matrix-org/matrix-doc/issues/1999>)
- [ ] Remove `prev_content` from the redaction algorithm's essential keys list. (<https://github.com/matrix-org/matrix-doc/issues/2016>)
- [ ] Fix the `third_party_signed` definitions for the join APIs. (<https://github.com/matrix-org/matrix-doc/issues/2025>)
- [ ] Clarify why User Interactive Auth is used on password changes and how access tokens are handled. (<https://github.com/matrix-org/matrix-doc/issues/2027>)
- [ ] Clarify that devices are deleted upon logout. (<https://github.com/matrix-org/matrix-doc/issues/2028>)
- [ ] Add `M_NOT_FOUND` error definition for deleting room aliases. (<https://github.com/matrix-org/matrix-doc/issues/2029>)
- [ ] Add missing `reason` to `m.call.hangup`. (<https://github.com/matrix-org/matrix-doc/issues/2031>)
- [ ] Clarify how redactions affect room state. (<https://github.com/matrix-org/matrix-doc/issues/2032>)
- [ ] Clarify that `FAIL_ERROR` in autodiscovery is not limited to just homeservers. (<https://github.com/matrix-org/matrix-doc/issues/2036>)
- [ ] Fix example `Content-Type` for `/media/upload` request. (<https://github.com/matrix-org/matrix-doc/issues/2041>)
- [ ] Clarify that login flows are meant to be completed in order. (<https://github.com/matrix-org/matrix-doc/issues/2042>)
- [ ] Clarify that clients should not send read receipts for their own messages. (<https://github.com/matrix-org/matrix-doc/issues/2043>)
- [ ] Use consistent examples of events throughout the specification. (<https://github.com/matrix-org/matrix-doc/issues/2051>)
- [ ] Clarify which push rule condition kinds exist. (<https://github.com/matrix-org/matrix-doc/issues/2052>)
- [ ] Clarify the required fields on `m.file` (and similar) messages. (<https://github.com/matrix-org/matrix-doc/issues/2053>)
- [ ] Clarify that User-Interactive Authentication stages cannot be attempted more than once. (<https://github.com/matrix-org/matrix-doc/issues/2054>)
- [ ] Clarify which parameters apply in what scenarios on `/register`. (<https://github.com/matrix-org/matrix-doc/issues/2055>)
- [ ] Clarify how to interpret changes of `membership` over time. (<https://github.com/matrix-org/matrix-doc/issues/2056>)
- [ ] Clarify exactly what invite_room_state consists of. (<https://github.com/matrix-org/matrix-doc/issues/2067>)
- [ ] Clarify how the content repository works, and what it is used for. (<https://github.com/matrix-org/matrix-doc/issues/2068>)
- [ ] Clarify the order events in chunk are returned in for `/messages`. (<https://github.com/matrix-org/matrix-doc/issues/2069>)
- [ ] Clarify the key object definition for the key management API. (<https://github.com/matrix-org/matrix-doc/issues/2083>)
- [ ] Reorganize information about events into a common section. (<https://github.com/matrix-org/matrix-doc/issues/2087>)
- [ ] De-duplicate `/state/<event_type>` endpoints, clarifying that the `<state_key>` is optional. (<https://github.com/matrix-org/matrix-doc/issues/2088>)
- [ ] Clarify when and where CORS headers should be returned. (<https://github.com/matrix-org/matrix-doc/issues/2089>)
- [ ] Clarify when authorization and rate-limiting are not applicable. (<https://github.com/matrix-org/matrix-doc/issues/2090>)
- [ ] Clarify that `/register` must produce valid Matrix User IDs. (<https://github.com/matrix-org/matrix-doc/issues/2091>)
- [ ] Clarify how `unread_notifications` is calculated. (<https://github.com/matrix-org/matrix-doc/issues/2097>)
- [ ] Clarify what a "module" is and update feature profiles for clients. (<https://github.com/matrix-org/matrix-doc/issues/2098>)
