### ISSUE TITLE
[meta] Tracking issue for r0.6.0 compatibility

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client#26]
*Based on [the changelog for r0.6.0](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst#r060). ToDo: Add new endpoints, implement upstream changes, review spec clarifications.*

Breaking Changes
----------------

- [ ] Add `id_access_token` as a required request parameter to a few endpoints which require an `id_server` parameter as part of [MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140). (<https://github.com/matrix-org/matrix-doc/issues/2255>)

New Endpoints
-------------

- [ ] Add `POST /account/3pid/unbind` for removing a 3PID from an identity server. (<https://github.com/matrix-org/matrix-doc/issues/2282>)

Backwards Compatible Changes
----------------------------

- [ ] Add `M_USER_DEACTIVATED` error code. (<https://github.com/matrix-org/matrix-doc/issues/2234>)
- [ ] Remove `bind_msisdn` and `bind_email` from `/register` now that the identity server's bind endpoint requires authentication. (<https://github.com/matrix-org/matrix-doc/issues/2279>)
- [ ] Add `m.identity_server` account data for tracking the user's preferred identity server. (<https://github.com/matrix-org/matrix-doc/issues/2281>)
- [ ] Deprecate `id_server` and make it optional in several places. (<https://github.com/matrix-org/matrix-doc/issues/2310>)

Spec Clarifications
-------------------

- [ ] Add missing format fields to `m.room.message$m.notice` schema. (<https://github.com/matrix-org/matrix-doc/issues/2125>)
- [ ] Remove "required" designation from the `url` field of certain `m.room.message` msgtypes. (<https://github.com/matrix-org/matrix-doc/issues/2129>)
- [ ] Fix various typos throughout the specification. (<https://github.com/matrix-org/matrix-doc/issues/2131>, <https://github.com/matrix-org/matrix-doc/issues/2136>, <https://github.com/matrix-org/matrix-doc/issues/2148>, <https://github.com/matrix-org/matrix-doc/issues/2215>)
- [ ] Clarify the distinction between `m.key.verification.start` and its `m.sas.v1` variant. (<https://github.com/matrix-org/matrix-doc/issues/2132>)
- [ ] Fix link to Olm signing specification. (<https://github.com/matrix-org/matrix-doc/issues/2133>)
- [ ] Clarify the conditions for the `.m.rule.room_one_to_one` push rule. (<https://github.com/matrix-org/matrix-doc/issues/2152>)
- [ ] Clarify the encryption algorithms supported by the device of the device keys example. (<https://github.com/matrix-org/matrix-doc/issues/2157>)
- [ ] Clarify that `/rooms/:roomId/event/:eventId` returns a Matrix error. (<https://github.com/matrix-org/matrix-doc/issues/2204>)
- [ ] Add a missing `state_key` check on `.m.rule.tombstone`. (<https://github.com/matrix-org/matrix-doc/issues/2223>)
- [ ] Fix the `m.room_key_request` `action` value, setting it from `cancel_request` to `request_cancellation`. (<https://github.com/matrix-org/matrix-doc/issues/2247>)
- [ ] Clarify that the `submit_url` field is without authentication. (<https://github.com/matrix-org/matrix-doc/issues/2341>)
- [ ] Clarify the expected phone number format. (<https://github.com/matrix-org/matrix-doc/issues/2342>)
- [ ] Clarify that clients should consider not requesting URL previews in encrypted rooms. (<https://github.com/matrix-org/matrix-doc/issues/2343>)
- [ ] Add missing information on how filters are meant to work with `/context`. (<https://github.com/matrix-org/matrix-doc/issues/2344>)
- [ ] Clarify what the keys are for rooms in `/sync`. (<https://github.com/matrix-org/matrix-doc/issues/2345>)
